# Generated by Django 2.0.5 on 2020-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='roomno',
            field=models.CharField(blank=True, choices=[('G1', 'G01'), ('G2', 'G102'), ('G3', 'G103'), ('G4', 'G104')], max_length=5, null=True),
        ),
    ]
