# Generated by Django 2.0.5 on 2020-07-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_booking_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='roomno',
        ),
    ]
