# Generated by Django 2.0.5 on 2020-08-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Cus',
        ),
    ]
